services:
  db:
    image: postgres:17-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Passw0rd
    ports:
      - 5432:5432

volumes:
  db:
